spring:
  datasource:
    url: jdbc:mysql://10.0.1.26:3306/getz?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1_800_000
  refreshToken-expiration-mills: 1_209_600_000

cookie:
  domain: getz.kr
  sameSite: None
  access-token-path: /
  refresh-token-path: /