spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret-key: thisissecretkeyisandeokgyun88012712859123jnqweasdpqwekjqwe
  accessToken-expiration-millis: 1_800_000
  refreshToken-expiration-mills: 1_209_600_000

cookie:
  domain: localhost
  sameSite: None
  access-token-path: /
  refresh-token-path: /